# Exported from Render on 2026-06-04T11:05:15Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: AgriSparks_mini
      runtime: node.js
      repo: https://github.com/AtharvaSonar-21/AgriSparks_mini
      plan: free
      region: singapore
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn your_application.wsgi
      autoDeployTrigger: commit
